//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYER
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string Position { get; set; }
        public string TEAM { get; set; }
        public Nullable<double> GP { get; set; }
        public Nullable<double> AGE { get; set; }
        public Nullable<double> W { get; set; }
        public Nullable<double> L { get; set; }
        public Nullable<double> MIN { get; set; }
        public Nullable<double> FGM { get; set; }
        public Nullable<double> FGA { get; set; }
        public Nullable<double> FG_ { get; set; }
        public Nullable<double> TPM { get; set; }
        public Nullable<double> TPA { get; set; }
        public Nullable<double> TP_ { get; set; }
        public Nullable<double> FTM { get; set; }
        public Nullable<double> FTA { get; set; }
        public Nullable<double> FT_ { get; set; }
        public Nullable<double> OREB { get; set; }
        public Nullable<double> DREB { get; set; }
        public Nullable<double> REB { get; set; }
        public Nullable<double> AST { get; set; }
        public Nullable<double> TOV { get; set; }
        public Nullable<double> STL { get; set; }
        public Nullable<double> BLK { get; set; }
        public Nullable<double> PF { get; set; }
        public Nullable<double> FP { get; set; }
        public Nullable<double> DD2 { get; set; }
        public Nullable<double> TD3 { get; set; }
        public Nullable<double> C___ { get; set; }
        public Nullable<double> RAT { get; set; }
        public Nullable<double> W_L { get; set; }
        public Nullable<double> PLAYERVALUE { get; set; }
    }
}
