//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERTEAM
    {
        public int ID { get; set; }
        public string User { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> Player1 { get; set; }
        public Nullable<int> Player2 { get; set; }
        public Nullable<int> Player3 { get; set; }
        public Nullable<int> Player4 { get; set; }
        public Nullable<int> Player5 { get; set; }
        public Nullable<int> Player6 { get; set; }
        public Nullable<int> Player7 { get; set; }
        public Nullable<int> Player8 { get; set; }
        public Nullable<int> Player9 { get; set; }
        public Nullable<int> Player10 { get; set; }
        public Nullable<int> Player11 { get; set; }
        public Nullable<int> Player12 { get; set; }
        public Nullable<int> Player13 { get; set; }
        public Nullable<int> Player14 { get; set; }
        public Nullable<int> Player15 { get; set; }
    }
}
